### ISSUE TITLE
Readme not correct

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360chores#69]
it seem like executing the single line as given in the current readme.md:

```
$ mvn install -P deploy -Ddeploy.dir=/ABSOLUTE/PATH/TO/sw360chores/_deploy -DskipTests
```

is not working, because maven vields the following message:

```
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce) @ sw360 ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireProperty failed with message:
You must set at least the property 'base.deploy.dir'!
```

rather the command could be (works for me):

```
mvn package -P deploy -Dbase.deploy.dir=/ABSOLUTE/PATH/TO/sw360chores/_deploy -Dliferay.deploy.dir=/ABSOLUTE/PATH/TO/sw360chores/_deploy/deploy -Dbackend.deploy.dir=/ABSOLUTE/PATH/TO/sw360chores/_deploy/tomcat-9.0.17/webapps -Drest.deploy.dir=/ABSOLUTE/PATH/TO/sw360chores/_deploy/tomcat-9.0.17/webapps -DskipTests
```

**Comment by maxhbr** [comment]
It should be sufficient to call
```
mvn package -P deploy -Dbase.deploy.dir=/ABSOLUTE/PATH/TO/sw360chores/_deploy -DskipTests
```

**Comment by camillem** [comment]
Hi, 
It seems it's not sufficient here, while @mcjaeger solution works (and then I run into another problem 
`- maven-thrift-plugin:0.1.11:compile (thrift-sources) @ datahandler ---
[ERROR] thrift failed output: [...] Type "RestApiToken" has not been defined.` ) but I guess it might be another story
Camille

**Comment by camillem** [comment]
After having started over with a more recent Ubuntu version (19.10, to get the proper version of Thrift), it seems to also work with the proposed short version.

**Comment by mcjaeger** [comment]
works also for me now.
